### ISSUE TITLE
Datenmodell besprechen

### ISSUE THREAD

**Issue by cfr9001** [InnoProj/Project-Management#25]
Sobald UserStories und die Requirements definiert wurden müssen wir gemeinsam das Datenmodell besprechen.

**Comment by hoegiDeveloping** [comment]
Das ist der Inital Comment von Michael

**Comment by cfr9001** [comment]
User "1" o--- "0..*" Event : creates ✅
Event "0..*" --- "1" User : has ❓
User "0.." --- "0.." Address : has ✅
Event "1" o--- "0..*" Address : has ❓müsste doch umgekehrt sein, oder?

**Comment by cfr9001** [comment]
class User {
    Firstname: string
    Lastname: string
    Age: int _-> berechnen?_
    Birthday: DateOnly
    UserRole: UserRoleType
    Address: Address_?_
    AreaCode: int_?_
    MobileNumber: int_?_
    Email: MailAddress
}

**Comment by cfr9001** [comment]
Ist der Ersteller eines Erlebnis nicht automatisch die ContactPerson?

```
class Event {
    Title: string
    Description: string
    EventStart: DateTime
    EventEnd: DateTime
    MinParticipants: int
    MaxParticipants: int
    Location: Address
    ContactPerson: User
}
```

**Comment by cfr9001** [comment]
➡️ Chat genauer besprechen

**Comment by cfr9001** [comment]
Wer genau kann Admin sein? Wie handeln wir Admins? Sind nur wir 4 Admins?

**Comment by cfr9001** [comment]
Wofür benötigen ChangedHistory bzw. wo wird dies benötigt?

**Comment by cfr9001** [comment]
> Wofür benötigen ChangedHistory bzw. wo wird dies benötigt?

knln

**Comment by merlinhuettl** [comment]
> Wofür benötigen ChangedHistory bzw. wo wird dies benötigt?

Die ChangedHistory Tabelle soll uns Administratoren helfen, nachvollziehen zu können, wann und welche Änderungen es an einem Event gab. Eine sogenannte "Änderungshistorie".

**Comment by merlinhuettl** [comment]
> Wer genau kann Admin sein? Sind nur wir 4 Admins?

Diese Frage verstehe ich nicht. :)

**Comment by merlinhuettl** [comment]
> User "1" o--- "0.._" Event : creates ✅ Event "0.._" --- "1" User : has ❓ User "0.." --- "0.." Address : has ✅ Event "1" o--- "0..*" Address : has ❓müsste doch umgekehrt sein, oder?

Hab ich angepasst, neues Modell ist bereits im Repository.

**Comment by hoegiDeveloping** [comment]
Im Repository vom ASP-Backend sind meine Ideen zum Datenmodell verbaut. Schaut gerne mal in die Domain rein. Chat ist tatsächlich nicht so einfach abzubilden, hab hier die TPC-Policy verwendet, die man bei abstrakten Klassen einsetzen kann.

**Comment by cfr9001** [comment]
@merlinhuettl bitte Datenmodell bis zum Coaching aktualisieren.
