### ISSUE TITLE
Klären: Ablauf bis zum Stattfinden eines Erlebnis

### ISSUE THREAD

**Issue by hoegiDeveloping** [InnoProj/Project-Management#27]
Frage: Ab wann werden Teilnehmer informiert, dass das Event fix stattfindet? -> Thema: Benachrichtigung bzw. Bekanntgabe der Adresse. 

Findet das Erlebnis per Default statt sobald die Mindestanzahl an Personen sich angemeldet hat? 
Oder muss der Veranstalter einen Button drücken, so dass die Teilnehmer informiert werden, dass es stattfindet?

Bis wann kann sich ein Nutzer von dem Erlebnis wieder abmelden? Bis zu ein Tag vorher? Wie machen wir das?

**Comment by cfr9001** [comment]
![Image](https://github.com/InnoProj/Project-Management/assets/160026810/ba65c7e3-d559-42f3-a190-9b18ab2f3807)

**Comment by cfr9001** [comment]
![Image](https://github.com/InnoProj/Project-Management/assets/160026810/4deb12f5-cabd-4b02-aeef-a13aa5677b4c)
