### ISSUE TITLE
Datenmodell: Wie bilden wir AllChat und SingleChat im Datenmodell ab?

### ISSUE THREAD

**Issue by hoegiDeveloping** [InnoProj/Project-Management#30]

**Comment by hoegiDeveloping** [comment]
Fragen:
- Ist ein private Chat im MVP
- Darf nur der Veranstalter im AllChat schreiben oder auch Teilnehmer?

**Comment by cfr9001** [comment]
Laut gemeinsamer Entscheidung ist Chat Prio 3 - somit nicht im MVP.

**Comment by cfr9001** [comment]
siehe aktuelles Datenmodell
