### ISSUE TITLE
Datenmodell überarbeiten (Chat, Beziehungen etc.)

### ISSUE THREAD

**Issue by mdu9669** [InnoProj/Project-Management#78]
#25 / #30 

![IMG_1714](https://github.com/InnoProj/Project-Management/assets/160026810/e800f957-8cc1-4040-ae02-2058ac37e61c)
![IMG_1713](https://github.com/InnoProj/Project-Management/assets/160026810/666e1425-1f06-4621-8070-ec3bcac71092)

**Comment by cfr9001** [comment]
siehe aktuelles Datenmodell

**Comment by cfr9001** [comment]
Das Datenmodell im Repo ist nicht auf dem aktuellen Stand. @hoegiDeveloping bitte das aktuelle Datenmodell hochladen.

Mitschrift Coaching vom 07.05. für @hoegiDeveloping:
- Registration EndDate für Erlebnisse hinzufügen (wird vom Veranstalter festgelegt)

**Comment by hoegiDeveloping** [comment]
Wie besprochen hier das aktuelle Datenmodell

[data-model_v_1.0.md](https://github.com/InnoProj/Project-Management/files/15442326/data-model_v_1.0.md)
